### ISSUE TITLE
Error spam in console 1.18 fabric

### ISSUE THREAD

**Issue by itsdinkd** [shedaniel/ClothConfig#134]
[04:13:51] [Server thread/FATAL]: Error executing task on Server
java.lang.RuntimeException: Cannot load class me.shedaniel.clothconfig2.api.AbstractConfigListEntry in environment type SERVER
        at Not Enough Crashes deobfuscated stack trace.(1.18+build.1) ~[?:?]
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:264) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.8.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraft.block.CropBlock.onUse(CropBlock:1552) ~[?:?]
        at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:937) ~[?:?]
        at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:327) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1056) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:30) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:780) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:162) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:762) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:756) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:110) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:740) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:688) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[intermediary-server-1.18.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[04:13:51] [Server thread/FATAL]: Error executing task on Server
java.lang.RuntimeException: Cannot load class me.shedaniel.clothconfig2.api.AbstractConfigListEntry in environment type SERVER
        at Not Enough Crashes deobfuscated stack trace.(1.18+build.1) ~[?:?]
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:264) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.8.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraft.block.CropBlock.onUse(CropBlock:1552) ~[?:?]
        at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:937) ~[?:?]
        at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:327) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1056) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:30) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:780) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:162) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:762) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:756) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:110) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:740) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:688) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[intermediary-server-1.18.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[04:13:51] [Server thread/FATAL]: Error executing task on Server
java.lang.RuntimeException: Cannot load class me.shedaniel.clothconfig2.api.AbstractConfigListEntry in environment type SERVER
        at Not Enough Crashes deobfuscated stack trace.(1.18+build.1) ~[?:?]
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:264) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.8.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraft.block.CropBlock.onUse(CropBlock:1552) ~[?:?]
        at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:937) ~[?:?]
        at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:327) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1056) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:30) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:780) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:162) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:762) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:756) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:110) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:740) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:688) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[intermediary-server-1.18.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[04:13:51] [Server thread/FATAL]: Error executing task on Server
java.lang.RuntimeException: Cannot load class me.shedaniel.clothconfig2.api.AbstractConfigListEntry in environment type SERVER
        at Not Enough Crashes deobfuscated stack trace.(1.18+build.1) ~[?:?]
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:264) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.8.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraft.block.CropBlock.onUse(CropBlock:1552) ~[?:?]
        at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:937) ~[?:?]
        at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:327) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1056) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:30) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:780) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:162) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:762) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:756) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:110) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:740) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:688) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[intermediary-server-1.18.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by shedaniel** [comment]
Not cloth's fault. a mod is loading cloth config on the server

**Comment by itsdinkd** [comment]
I'll look into it. Thanks
