### ISSUE TITLE
v12.0.109 causes crash on Forge modpack when clicking Config for this mod itself

### ISSUE THREAD

**Issue by TBlazeWarriorT** [shedaniel/ClothConfig#229]
**Issue:**
Crash when selecting [[LexForge 1.20.2] v12.0.109](https://modrinth.com/mod/cloth-config/version/12.0.109+forge) on the Mods menu and clicking Config near Open mods folder
`[Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: mouseClicked event handler`
`Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.client.gui.components.EditBox.m_94198_(boolean)'`

**Solution:**
Downgrading to one version older (can't reproduce on [[Forge 1.20(.1)] v11.1.106](https://modrinth.com/mod/cloth-config/version/11.1.106+forge))

**Seemingly useful log:**
`[22Nov2023 12:59:56.345] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: mouseClicked event handler
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:444) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:189) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:188) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.3.1.jar%2364!/:build 7]
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133) ~[FpsReducer2-forge-1.20-2.5.jar%23252!/:1.20-2.5]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%2364!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%2370!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar%2364!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.handler$zej000$handleWaitEventsTimeout(RenderSystem.java:1508) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1173) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[?:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[?:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.client.gui.components.EditBox.m_94198_(boolean)'
	at me.shedaniel.clothconfig2.gui.entries.AbstractTextFieldListListEntry$AbstractTextFieldListCell.<init>(AbstractTextFieldListListEntry.java:87) ~[cloth-config-12.0.109-forge.jar%23231!/:?]
	at me.shedaniel.clothconfig2.gui.entries.DoubleListListEntry$DoubleListCell.<init>(DoubleListListEntry.java:77) ~[cloth-config-12.0.109-forge.jar%23231!/:?]
	at me.shedaniel.clothconfig2.gui.entries.AbstractListListEntry.<init>(AbstractListListEntry.java:57) ~[cloth-config-12.0.109-forge.jar%23231!/:?]
	at me.shedaniel.clothconfig2.gui.entries.AbstractTextFieldListListEntry.<init>(AbstractTextFieldListListEntry.java:55) ~[cloth-config-12.0.109-forge.jar%23231!/:?]
	at me.shedaniel.clothconfig2.gui.entries.DoubleListListEntry.<init>(DoubleListListEntry.java:54) ~[cloth-config-12.0.109-forge.jar%23231!/:?]
	at me.shedaniel.clothconfig2.impl.builders.DoubleListBuilder.build(DoubleListBuilder.java:151) ~[cloth-config-12.0.109-forge.jar%23231!/:?]
	at me.shedaniel.clothconfig2.ClothConfigDemo.getConfigBuilderWithDemo(ClothConfigDemo.java:94) ~[cloth-config-12.0.109-forge.jar%23231!/:?]
	at me.shedaniel.clothconfig.ClothConfigForgeDemo.lambda$registerModsPage$0(ClothConfigForgeDemo.java:29) ~[cloth-config-12.0.109-forge.jar%23231!/:?]
	at net.minecraftforge.client.gui.ModListScreen.lambda$displayModConfig$6(ModListScreen.java:303) ~[forge-1.20.1-47.2.0-universal.jar%23311!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.client.gui.ModListScreen.displayModConfig(ModListScreen.java:303) ~[forge-1.20.1-47.2.0-universal.jar%23311!/:?]
	at net.minecraftforge.client.gui.ModListScreen.lambda$init$2(ModListScreen.java:268) ~[forge-1.20.1-47.2.0-universal.jar%23311!/:?]
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:38) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?]
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:55) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?]
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:175) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:38) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:92) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?]
	... 42 more
[22Nov2023 12:59:56.355] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 0069620f-de1e-43a2-a388-28108bf5b25f
[22Nov2023 12:59:56.360] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 0d5ac032-ef14-4e0f-b466-8a77c65036f5
`

**Crash Log (seems less useful than the regular log above):**
[crash-2023-11-22_12.59.56-client.txt](https://github.com/shedaniel/cloth-config/files/13441871/crash-2023-11-22_12.59.56-client.txt)

**Comment by NovaViper** [comment]
Having the same issue here aswell on 1.20.1 with Forge v47.2.0. In fact because of this issue, other mods like [Expanded Combat](https://github.com/userofbricks/Expanded-Combat/issues/33) that rely on Cloth Config completely break, all having the same exact error

**Comment by NovaViper** [comment]
🤔 Now that broad sword issue.. it's directly related with Better Combat, because even with just strictly Expanded Combat and Better Combat (and their dependencies), it still registers as a two-handed weapon and not a one-handed weapon
