### ISSUE TITLE
missing cloth config eventhough it is installed

### ISSUE THREAD

**Issue by FRERFIII** [shedaniel/ClothConfig#248]
Crashes upon startup due to incomatible mods.

says i need to install cloth config2 11.0.99 or later and cloth config 10.0.0 or later allthough i installed them.

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install cloth-config2, version 11.0.99 or later.
	 - Install puzzleslib, version 8.1.13 or later.
	 - Install cloth-config, version 10.0.0 or later.
	 - Install moonlight, version 1.20-2.7.0 or later.
More details:
	 - Mod 'AdditionZ' (additionz) 1.3.1 requires version 11.0.99 or later of cloth-config2, which is missing!
	 - Mod 'Better Animations Collection' (betteranimationscollection) 8.0.0 requires version 8.0.0 or later of puzzleslib, which is missing!
	 - Mod 'Camera Overhaul' (cameraoverhaul) 1.4.0-fabric-universal requires version 4.8.3 or later of cloth-config2, which is missing!
	 - Mod 'Connectible Chains' (connectiblechains) 2.2.1+1.20.1 requires version 8.2.88 or later of cloth-config2, which is missing!
	 - Mod 'Diagonal Fences' (diagonalfences) 8.1.4 requires version 8.1.13 or later of puzzleslib, which is missing!
	 - Mod 'Diagonal Blocks' (diagonalblocks) 8.0.5 requires version 8.1.5 or later of puzzleslib, which is missing!
	 - Mod 'Falling Leaves' (fallingleaves) 1.15.5 requires version 10.0.0 or later of cloth-config, which is missing!
	 - Mod 'Immersive Weathering' (immersive_weathering) 1.20.1-2.0.2 requires version 1.20-2.7.0 or later of moonlight, which is missing!
	 - Mod 'Visuality' (visuality) 0.7.1+1.20 requires any version of cloth-config, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

![grafik](https://github.com/shedaniel/cloth-config/assets/165436881/66b55a42-5d14-4836-aa53-b3f6fb428145)

**Comment by FRERFIII** [comment]
i am a moron, forgett it lol, i installed the forge version. sry for the spam
