### ISSUE TITLE
Crash in dev environment

### ISSUE THREAD

**Issue by qouteall** [shedaniel/ClothConfig#28]
I used 
`modApi "me.shedaniel.cloth:config-2:2.9.3"`
in build.gradle.
When I clicked the mods button, it crashed 
`
java.lang.NoSuchMethodError: net.minecraft.client.texture.TextureManager.method_4616(Lnet/minecraft/util/Identifier;Lnet/minecraft/client/texture/AbstractTexture;)Z
	at io.github.prospector.modmenu.gui.ModListEntry.bindIconTexture(ModListEntry.java:119)
	at io.github.prospector.modmenu.gui.ModListEntry.render(ModListEntry.java:49)
	at io.github.prospector.modmenu.gui.ModListWidget.renderList(ModListWidget.java:227)
`
This may be caused by yarn names mismatch.
I am using yarn mapping 1.15.2+build.14

**Comment by shedaniel** [comment]
![image](https://user-images.githubusercontent.com/34910653/75131665-1a901e80-570f-11ea-96e3-52a57ee82408.png)

**Comment by shedaniel** [comment]
https://shedaniel.gitbook.io/cloth-config/advanced/modmenu-integration
