### ISSUE TITLE
something broke (1.16.3)

### ISSUE THREAD

**Issue by HetNeSS** [shedaniel/ClothConfig#64]
Game crash upon clicking "settings" button on mod manager, as well as trying to open REI's hud by ctrl+o.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2020-11-05 18:53:43 YEKT
Description: Rendering screen

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
    at Not Enough Crashes deobfuscated stack trace.(1.16.3+build.47)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
    at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
    at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
    at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at me.shedaniel.clothconfig2.api.ScissorsHandler.<clinit>(ScissorsHandler.java:12)
    at me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget.render(DynamicEntryListWidget.java:199)
    at me.shedaniel.clothconfig2.gui.widget.DynamicNewSmoothScrollingEntryListWidget.render(DynamicNewSmoothScrollingEntryListWidget.java:136)
    at me.shedaniel.clothconfig2.gui.ClothConfigScreen.render(ClothConfigScreen.java:237)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:616)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1023)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:656)
    at net.minecraft.client.main.Main.main(Main:215)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in me/shedaniel/clothconfig2/impl/ScissorsHandlerImpl::applyScissors()V has incompatible changes at opcode 112 in callback me/shedaniel/clothconfig2/impl/ScissorsHandlerImpl::applyScissorsOffset.
Expected: [Lme/shedaniel/math/Rectangle;]
   Found: []
    at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497)
    at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:447)
    at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264)
    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385)
    at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284)
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
    at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
    ... 29 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Screen render details --
  Screen name: me.shedaniel.clothconfig2.gui.ClothConfigScreen
  Mouse location: Scaled: (626, 57). Absolute: (1879.000000, 172.000000)
  Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3.000000

-- System Details --
  Minecraft Version: 1.16.3
  Minecraft Version ID: 1.16.3
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_271, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 9169390840 bytes (8744 MB) / 9643753472 bytes (9197 MB) up to 13362528256 bytes (12743 MB)
  CPUs: 16
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx14336m
  Suspected Mods: Fabric Loader (fabricloader), Cloth Config v4 (cloth-config2)
  Fabric Mods: artifice: Artifice 0.13.1+1.16.2-rc1
               autoconfig1u: Auto Config v1 Updated 3.3.1
               better_mod_button: Better Mod Button 1.1.4
               cloth-api: Cloth API 1.4.9
               cloth-armor-api-v1: Cloth Armor API v1 1.4.9
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.9
               cloth-common-events-v1: Cloth Common Events v1 1.4.9
               cloth-config2: Cloth Config v4 4.8.3
               cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
               cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
               cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
               cloth-scissors-api-v1: Cloth Scissors API v1 1.4.9
               cloth-utils-v1: Cloth Utils v1 1.4.9
               colormatic: Colormatic 2.2.7+mc.1.16.3
               durabilityviewer: Giselbaers Durability Viewer 1.16.2-fabric0.17.2-1.8.7
               dynamicfps: Dynamic FPS 1.2.1
               fabric: Fabric API 0.25.0+build.415-1.16
               fabric-api-base: Fabric API Base 0.2.0+9f0fb4b895
               fabric-biome-api-v1: Fabric Biome API (v1) 3.0.0+8367596d95
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
               fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a95
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a95
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a95
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
               fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
               fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab95
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a95
               fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a95
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a95
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a95
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
               fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
               fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a95
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+2b46237995
               fabricloader: Fabric Loader 0.10.6+build.214
               fabrishot: Fabrishot 1.2.1
               fiber: fiber 0.23.0-2
               gbfabrictools: GBfabrictools 1.2.3+1.16.2
               harvest: Harvest 1.2.12
               lambdynlights: LambDynamicLights 1.3.1+1.16.3
               lithium: Lithium 0.5.6
               loadcatcher: Entrypoint Catcher 2.0.0
               minecraft: Minecraft 1.16.3
               mm: Manningham Mills 2.1
               modmenu: Mod Menu 1.14.6+build.31
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.1
               okzoomer: Ok Zoomer 4.0.1+1.16.2
               org_codehaus_groovy_groovy: groovy 3.0.3
               org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
               org_jetbrains_annotations: annotations 20.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
               phosphor: Phosphor 0.6.0+build.7
               raisedclouds: Raised Clouds 1.0.0
               roughlyenoughitems: Roughly Enough Items 5.8.1
               roughlyenoughitems-api: REI (API) 5.8.1
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.1
               roughlyenoughitems-runtime: REI (Runtime) 5.8.1
               roughlyenoughresources: Roughly Enough Resources 2.1.2
               slight-gui-modifications: 'Slight' GUI Modifications 1.5.0
               smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
               sodium: Sodium 0.1.0
               spruceui: SpruceUI 1.6.4
               torohealth: ToroHealth Damage Indicators 1.16.3-fabric-1
               xaeroworldmap: Xaero's World Map 1.11.0
  Launched Version: MultiMC5
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: GeForce GTX 950/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.09, NVIDIA Corporation
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Graphics mode: fancy
  Resource Packs: vanilla, slightguimodifications:cts_textures, fabric/fabric-renderer-api-v1, fabric/fabric-keybindings-v0, fabric/notenoughcrashes, fabric/fabricloader, fabric/artifice, fabric/lithium, fabric/fabric-containers-v0, fabric/fabric-object-builder-api-v1, fabric/fabric-game-rule-api-v1, fabric/fabric-api-base, fabric/mm, fabric/fabric-rendering-data-attachment-v1, fabric/lambdynlights, fabric/fabric-textures-v0, fabric/fabric-rendering-fluids-v1, fabric/raisedclouds, fabric/fabric-blockrenderlayer-v1, fabric/fabric-lifecycle-events-v1, fabric/sodium, fabric/fabric-renderer-registries-v1, fabric/fabric-loot-tables-v1, fabric/fabric, fabric/dynamicfps, fabric/fabric-networking-v0, fabric/okzoomer, fabric/fabric-networking-blockentity-v0, fabric/fabric-screen-handler-api-v1, fabric/modmenu, fabric/fabrishot, fabric/phosphor, fabric/fabric-tool-attribute-api-v1, fabric/fabric-renderer-indigo, fabric/fabric-crash-report-info-v1, fabric/fabric-events-interaction-v0, fabric/fabric-item-api-v1, fabric/fabric-language-kotlin, fabric/slight-gui-modifications, fabric/fabric-rendering-v0, fabric/fabric-key-binding-api-v1, fabric/fabric-rendering-v1, fabric/cloth-config2, fabric/better_mod_button, fabric/spruceui, fabric/smoothscrollingeverywhere, fabric/autoconfig1u, fabric/fabric-resource-loader-v0, fabric/fabric-content-registries-v0, fabric/fabric-tag-extensions-v0, fabric/fabric-biome-api-v1, fabric/colormatic, fabric/fabric-registry-sync-v0, fabric/fabric-mining-levels-v0, fabric/fabric-events-lifecycle-v0, fabric/fabric-item-groups-v0, fabric/fabric-models-v0, fabric/fabric-object-builders-v0, fabric/harvest, fabric/torohealth, fabric/roughlyenoughitems, fabric/roughlyenoughitems-runtime, fabric/xaeroworldmap, file/Soartex_Fanver_(8.0.2).zip, fabric/durabilityviewer, fabric/fabric-command-api-v1, fabric/gbfabrictools, fabric/roughlyenoughresources, file/Leviosa.zip (incompatible)
  Current Language: Русский (Россия)
  CPU: 16x Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

**Comment by HetNeSS** [comment]
Full console stack - https://paste.ee/p/1VteM

**Comment by shedaniel** [comment]
Thanks for reporting, I will get on this later

**Comment by shedaniel** [comment]
Please update slight gui modifications
